#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

nuget:
  account_feed: true
  project_feed: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  project: Imp.PosiStageDotNet.sln
  publish_nuget: true
  publish_nuget_symbols: true


#---------------------------------#
#           build events          #
#---------------------------------#

before_build:
  - nuget restore
  
#---------------------------------#
#              deploy             #
#---------------------------------#
 
deploy:
  provider: NuGet
  api_key:
    secure: rWUYkrDdoedwz/r2XGss/gQ4j9+oRVw/4t5j48vDRFN9sM9Tyl0zlUAby5MMm3ME
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true