#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

nuget:
  account_feed: true
  project_feed: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform: Any CPU

configuration: Release

build:
  project: Imp.PosiStageDotNet.sln
  publish_nuget: true
  publish_nuget_symbols: true


#---------------------------------#
#           build events          #
#---------------------------------#

before_build:
  - nuget restore