#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master
    - develop

#---------------------------------#
#    environment configuration    #
#---------------------------------#

nuget:
  account_feed: true
  project_feed: true

#---------------------------------#
#       build configuration       #
#---------------------------------#

build:
  project: Imp.PosiStageDotNet.sln
  publish_nuget: true
  publish_nuget_symbols: true


#---------------------------------#
#           build events          #
#---------------------------------#

before_build:
  - ps: if (Test-Path 'C:\Tools\NuGet3') { $nugetDir = 'C:\Tools\NuGet3' } else { $nugetDir = 'C:\Tools\NuGet' }
  - ps: (New-Object Net.WebClient).DownloadFile('https://dist.nuget.org/win-x86-commandline/v3.4.3/nuget.exe', "$nugetDir\NuGet.exe")
  - nuget sources add -Name DotNet-Core -Source https://dotnet.myget.org/f/dotnet-core/api/v3/index.json
  - nuget restore
  
#---------------------------------#
#              deploy             #
#---------------------------------#
 
deploy:
  provider: NuGet
  api_key:
    secure: rWUYkrDdoedwz/r2XGss/gQ4j9+oRVw/4t5j48vDRFN9sM9Tyl0zlUAby5MMm3ME
  skip_symbols: false
  on:
    branch: master
    appveyor_repo_tag: true